//! CLI command implementations.

mod add;
mod assemble;
mod bisect;
mod blame;
mod branch;
mod cache_stats;
mod checkout;
mod cherry_pick;
mod clone;
mod commit;
mod config;
mod dependency;
mod diff;
mod fetch;
mod fsck;
mod gc;
mod init;
mod inspect;
mod inspect_file;
mod lifecycle;
mod lock;
mod log;
mod merge;
mod meta;
pub mod p2p;
#[cfg(feature = "fuser")]
mod mount;
mod proxy;
mod pull;
mod push;
mod rebase;
mod reflog;
mod remote;
mod repo_stats;
mod reset;
mod restore;
mod roundtrip;
mod security;
mod segment;
mod show;
mod stash;
mod status;
mod tag;
#[cfg(feature = "fuser")]
mod unmount;
mod video;

pub use add::add;
pub use assemble::assemble;
pub use bisect::bisect;
pub use blame::blame;
pub use branch::{branch, switch};
pub use cache_stats::cache_stats;
pub use checkout::{checkout, CheckoutMode};
pub use cherry_pick::cherry_pick;
pub use clone::clone;
pub use commit::commit;
pub use config::config;
pub use dependency::{dep_check, dep_graph, dep_list};
pub use diff::diff;
pub use fetch::fetch;
pub use fsck::fsck;
pub use gc::gc;
pub use init::init;
pub use inspect::inspect;
pub use inspect_file::inspect_file;
pub use lifecycle::{freeze_init, freeze_status, freeze, thaw, freeze_policy};
pub use lock::{lock, unlock, locks};
pub use log::log;
pub use merge::merge;
pub use meta::{meta_scan, meta_show, meta_list};
pub use p2p::handle_p2p_command;
#[cfg(feature = "fuser")]
pub use mount::mount;
pub use proxy::{proxy_generate, proxy_status, proxy_list, proxy_delete};
pub use pull::pull;
pub use push::push;
pub use rebase::rebase;
pub use reflog::reflog;
pub use remote::remote;
pub use repo_stats::repo_stats;
pub use reset::{reset, ResetMode};
pub use restore::restore;
pub use roundtrip::roundtrip;
pub use security::{encrypt_init, encrypt_status, login, logout, change_password, audit_show, audit_stats, audit_export};
pub use segment::segment;
pub use show::show;
pub use stash::stash;
pub use status::status;
pub use tag::tag;
#[cfg(feature = "fuser")]
pub use unmount::unmount;
pub use video::{video_init, video_add_clip, video_show, video_list};
